"""End-to-end analysis: Pareto -> price elasticity -> experiment design. Writes reports/RESULTS.md and figures."""

from __future__ import annotations

import sys
from pathlib import Path

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))

from pricing_lab import data, elasticity, experiments, pareto  # noqa: E402

FIG = ROOT / "reports" / "figures"
FIG.mkdir(parents=True, exist_ok=True)


def main() -> None:
    data.download_raw()
    con = data.connect()
    lines = ["# Results", "", "Generated by `python scripts/run_analysis.py` on the UCI Online Retail II dataset (Dec 2009 - Dec 2011).", ""]

    # 1. Pareto: where does revenue concentrate?
    prod = con.execute("SELECT * FROM product_revenue").df()
    pt = pareto.pareto_table(prod, "revenue", "stock_code")
    n80 = pareto.items_for_share(pt, 0.8)
    fig, ax = plt.subplots(figsize=(7, 4))
    ax.plot(pt["cum_items_share"] * 100, pt["cum_share"] * 100)
    ax.axhline(80, ls="--", c="gray")
    ax.set(xlabel="% of products (sorted by revenue)", ylabel="% of revenue", title="Revenue Pareto curve")
    fig.tight_layout(); fig.savefig(FIG / "pareto.png", dpi=150); plt.close(fig)
    lines += ["## 1. Revenue concentration (Pareto)", "",
              f"- {len(pt):,} products; the top **{n80:,} ({n80 / len(pt):.1%})** generate 80% of revenue.",
              "- Elasticity work below focuses on products with enough history and price variation.", "",
              "![pareto](figures/pareto.png)", ""]

    # 2. Price elasticity
    weekly = con.execute("SELECT * FROM product_weekly").df()
    naive = elasticity.pooled_elasticity(elasticity.prepare_panel(weekly, price_col="avg_price"))
    panel = elasticity.prepare_panel(weekly, price_col="list_price")
    pooled = elasticity.pooled_elasticity(panel)
    per = elasticity.per_product_elasticities(panel)
    shrunk, eb = elasticity.empirical_bayes_shrink(per)
    shrunk = shrunk.merge(prod[["stock_code", "description", "revenue"]], on="stock_code")
    shrunk.sort_values("revenue", ascending=False).to_csv(ROOT / "reports" / "elasticities.csv", index=False)

    fig, ax = plt.subplots(figsize=(7, 4))
    bins = np.linspace(-6, 3, 46)
    ax.hist(per["beta"].clip(-6, 3), bins=bins, alpha=0.5, label="per-product OLS")
    ax.hist(shrunk["beta_shrunk"].clip(-6, 3), bins=bins, alpha=0.7, label="empirical-Bayes shrunk")
    ax.axvline(-1, ls="--", c="k", lw=1)
    ax.set(xlabel="own-price elasticity", ylabel="products", title="Elasticity estimates before/after shrinkage")
    ax.legend(); fig.tight_layout(); fig.savefig(FIG / "elasticities.png", dpi=150); plt.close(fig)

    elastic = (shrunk["beta_shrunk"] < -1).mean()
    lines += ["## 2. Price elasticity", "",
              f"- Panel: {pooled['n_obs']:,} product-weeks, {pooled['n_products']} UK products with >= 40 weeks and real list-price variation.",
              f"- Naive model on *average price paid*: {naive['beta']:.2f}. This is biased: bulk orders get volume discounts, so a big week "
              "mechanically lowers the average price (reverse causality from quantity to price).",
              f"- Using the weekly *median list price* instead: **{pooled['beta']:.2f}** (95% CI {pooled['ci_low']:.2f} to {pooled['ci_high']:.2f}, "
              "within-product, month seasonality, SE clustered by product).",
              f"- Per-product estimates are noisy; empirical-Bayes shrinkage toward mu = {eb['mu']:.2f} (between-product sd tau = {eb['tau']:.2f}).",
              f"- After shrinkage, {elastic:.0%} of products look elastic (beta < -1): price cuts there are more likely to raise revenue.",
              "- These are observational associations (prices move with order size and promotions). Use them to **prioritize** which products to test, not as final causal estimates.",
              "", "![elasticities](figures/elasticities.png)", ""]

    # 3. Experiment design with CUPED on real customer spend
    cust = con.execute("SELECT pre_spend, post_spend FROM customer_periods").df()
    y = cust["post_spend"].clip(upper=cust["post_spend"].quantile(0.99)).to_numpy()
    x = cust["pre_spend"].clip(upper=cust["pre_spend"].quantile(0.99)).to_numpy()
    y_adj, theta = experiments.cuped(y, x)
    var_red = 1 - y_adj.var() / y.var()
    lift = 0.05
    mde = lift * y.mean()
    n_raw = experiments.sample_size_per_arm(y.std(ddof=1), mde)
    n_cuped = experiments.sample_size_per_arm(y_adj.std(ddof=1), mde)
    fpr = experiments.simulate_power(y, x, lift=0.0, n_sims=500, use_cuped=True, seed=1)
    pw_raw = experiments.simulate_power(y, x, lift=0.10, n_sims=500, seed=2)
    pw_cuped = experiments.simulate_power(y, x, lift=0.10, n_sims=500, use_cuped=True, seed=2)
    lines += ["## 3. Experiment design: how many customers does a price test need?", "",
              f"- Outcome: customer spend Jun-Aug 2011 ({len(y):,} customers); covariate: spend Mar-May 2011.",
              f"- CUPED (theta = {theta:.2f}) removes **{var_red:.0%}** of outcome variance.",
              f"- To detect a 5% lift in spend (80% power, alpha 5%): **{n_raw:,}** customers per arm without CUPED vs **{n_cuped:,}** with CUPED.",
              f"- Simulated A/A tests with CUPED: false-positive rate {fpr:.1%} (target 5%).",
              f"- Simulated 10% lift on the real customer base: power {pw_raw:.0%} without CUPED vs {pw_cuped:.0%} with CUPED.",
              "- Note: the lift in these simulations is injected; the purpose is to size and validate the test design before running it.", ""]

    (ROOT / "reports" / "RESULTS.md").write_text("\n".join(lines), encoding="utf-8")
    print("\n".join(lines))


if __name__ == "__main__":
    main()
